### ISSUE TITLE
1.0.0 Roadmap

### ISSUE THREAD

**Issue by vovayatsyuk** [breezefront/module-breeze#1]
- [x] Register all known components in the 'breeze.js' block.
- [x] Inject components declared inside ko templates (MSRP)
- [x] Add 'enabled' key to all possible components to remove them from bundle when module/config is disabled.
- [x] Disable module on unknown pages.
- [x] Allow multiple aliases for single component
- [x] ~~Remove all unknown components from the dom structure.~~
- [x] Describe dependencies between components to include all required bundles on the page.
- [x] Do not use assets? (Split into multiple bundles) (Test in production mode with bundling/merge)
- [x] MSRP
- [x] Paypal buttons
- [x] Cookie restriction
- [x] Cart popup
- [x] quickSearch
- [x] Password strength (remove)
- [x] Allow remote shopping assistance during registration (check)
- [x] Breadcrumbs
- [x] Esi block (pageCache)
- [x] Reviews
- [x] Related
- [x] Upsells
- [x] Validator (methodName.apply bug)
- [x] Mobile search
- [x] Recently viewed
- [x] Account page
- [x] Gallery/Lightbox
- [x] GoogleAnalytics
- [x] ~~Cart page~~
- [x] ~Auth popup~
- [x] ~Magento_Customer/js/invalidation-processor~
- [x] ~mage/trim-input~
- [x] ~Magento_InstantPurchase/js/view/instant-purchase~
